name: Bug Report
description: Report a problem or unexpected behavior
title: "[BUG][PORT-<ISSUE_NUMBER>] Bug Report title"
labels: [bug]

body:
  - type: textarea
    attributes:
      label: 🐛 Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🧪 To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🎯 Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📷 Evidences
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Paste images or links here.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: 🖥️ Desktop
      description: Please complete the following information
      options:
        - OS: Windows
        - OS: macOS
        - OS: Linux
        - Other
    validations:
      required: false

  - type: input
    attributes:
      label: 🖥️ Desktop Browser
      placeholder: e.g. Chrome, Safari, Firefox
    validations:
      required: false

  - type: input
    attributes:
      label: 🖥️ Desktop Browser Version
      placeholder: e.g. 22
    validations:
      required: false

  - type: input
    attributes:
      label: 📱 Smartphone Device
      placeholder: e.g. iPhone 6
    validations:
      required: false

  - type: input
    attributes:
      label: 📱 Smartphone OS
      placeholder: e.g. iOS 8.1 / Android 13
    validations:
      required: false

  - type: input
    attributes:
      label: 📱 Smartphone Browser
      placeholder: e.g. Safari, Chrome
    validations:
      required: false

  - type: input
    attributes:
      label: 📱 Smartphone Browser Version
      placeholder: e.g. 22
    validations:
      required: false
