name: General Issue
description: Feature, enhancement or general suggestion for the project
title: "[TURMA-<ISSUE_ID>][SUB-<SUB_ISSUE_ID>] Title resuming the issue"

body:
  - type: textarea
    attributes:
      label: 🚀 Description
      placeholder: |
        You can describe with a clear and concise description of:
        * what the problem is
        * what you want to happen
        * any alternative solutions or features you've considered
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🧑‍💻 User stories
      placeholder: |
        Describe user stories in the format:
        * As a [type of user], I want [goal] so that [reason/benefit]
        * When [type of user] does [some system input/action], the [app part] must [expected behavior]... [other requirements/expectations]

        Example:
        * As a developer, I want to see code examples so that I can understand how to implement the feature
        * As an end user, I want a responsive interface so that I can access the app on any device
    validations:
      required: false

  - type: textarea
    attributes:
      label: 🥸 Technical Refinement
      placeholder: |
        You can describe technical details, considerations, or constraints related to the issue.
        * Architecture changes
        * Data models
        * API endpoints
        * Performance considerations
        * Security implications
    validations:
      required: false

  - type: textarea
    attributes:
      label: 📷 References / 🔗 Attachments
      placeholder: |
        You can attach some screenshots or links here.
        * Desktop
        * Mobile
        * Links
        * [some link]()
    validations:
      required: false
